
all:
	cd Tools && make
	cd libiniparser && make
	cd Logging && make
	cd PSPApp && make

clean:
	cd lib && rm -f *.a 
	cd Tools && make clean
	cd libiniparser && make clean
	cd Logging && make clean
	cd PSPApp && make clean 
