
all:
	cd lib && rm *.a
	cd Tools && make clean all
	cd libpspnet && make clean all
	cd libiniparser && make clean all
	cd Logging && make clean all
	cd PSPApp && make clean all
	cd libsamplerate && make clean all
