##
## iniparser test Makefile (linux binary)
##

CC = gcc
PNAME = initest

CFLAGS = $(INCLUDES) -O1 -Wall -Werror -g -DLINUX

LIBS = ../../SharedLib/Tools/Tools.o ./iniparser.o
INCLUDES = -I. -I../../SharedLib/Tools -I../../SharedLib/Tools

OBJS = Test.o

all: $(OBJS)
	$(CC) $(CFLAGS) $(LIBS) $(OBJS) -o $(PNAME)

.c.o:
	$(CC) $(CFLAGS) -c $*.c
