CC=gcc
PNAME=ThemeTool

LIBS=-lSDL -lSDLmain -lstdc++
INC=-I. -I./SharedLibLinux

CFLAGS=$(INC) -O1 -Wall -g -DLINUX

OBJS=./SharedLibLinux/Logging.o ./SharedLibLinux/iniparser.o GraphicsUITheme.o ThemeTool.o

all: $(OBJS)
	$(CC) $(CFLAGS) $(LIBS) $(OBJS) -o $(PNAME)

.cpp.o:
	$(CC) $(CFLAGS) -c $*.cpp

clean:
	rm -f *.o
	rm -f $(PNAME)
