### 
## Linux Tools library makefile (linux version -- for testing)
###

GCC = gcc
LD = ld
AR = ar
RANLIB = ranlib

#PSPSDK		= $(shell psp-config --pspsdk-path)

CFLAGS		=-O0 -Wall -g -I. -DLINUX
ASFLAGS		=x -g -O2 -G0 -Wall -I.

LIB =../lib/Tools-linux.a
OBJS  = Tools.o

all: $(LIB)

$(LIB): $(OBJS)
	$(AR) r $(LIB) $(OBJS)

.c.o:
	$(GCC) $(CFLAGS) -c $*.c

.S.o:
	$(GCC) $(ASFLAGS) -c $*.S

clean:
	rm -f *.o $(LIB)
