include ./Makefile

KXPLOIT_PRIMARY_DIR = "Harbringer-iconset/PSPRadio"
KXPLOIT_SECONDARY_DIR = "Harbringer-iconset/PSPRadio%"

PSP_EBOOT_ICON = resources_harbringer/icon0.png
PSP_EBOOT_PIC1 = resources_harbringer/pic1.png


