include ./Makefile

KXPLOIT_PRIMARY_DIR = "Handojin-iconset/PSPRadio"
KXPLOIT_SECONDARY_DIR = "Handojin-iconset/PSPRadio%"

PSP_EBOOT_ICON = resources_handojin/ICON0.png
PSP_EBOOT_PIC1 = resources_handojin/PIC1.png

