include Makefile

TARGET_LIB = ../lib/libPSPApp_debug.a

CFLAGS = -O0 -G0 -ggdb -DDEBUG -Wall -D__PSP__ $(INCLUDES)

CXXFLAGS = $(CFLAGS) 
#-fno-exceptions -fno-rtti
ASFLAGS = $(CFLAGS)

PSPSDK=$(shell psp-config --pspsdk-path)
include $(PSPSDK)/lib/build.mak
